AppCoder/urls.py
from django.urls import path
from AppCoder import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path('inicio', views.inicio, name='inicio'),
    path('clubes', views.club, name='Clubes'),
    path('jugadora', views.jugadora, name='Jugadoras'),
    path('torneo', views.torneo, name='Torneo'),
    path('buscar/', views.buscar),

    path('club/lista', views.ClubList.as_view(), name='ListClubes'),
    path(r'^(?P<pk>\d+)$', views.ClubDetalle.as_view(), name='Detail'),
    path(r'^nuevo$', views.ClubCreacion.as_view(), name='New'),
    path(r'^editar/(?P<pk>\d+)$', views.ClubUpdate.as_view(), name='Edit'),
    path(r'^borrar/(?P<pk>\d+)$', views.ClubDelete.as_view(), name='Delete'),

    path('jugadora/lista', views.JugadoraList.as_view(), name='ListJugadora'),
    path(r'^(?P<pk>\d+)$1', views.JugadoraDetalle.as_view(), name='DetailJugadora'),
    path(r'^nuevo1$', views.JugadoraCreacion.as_view(), name='NewJugadora'),
    path(r'^editar/(?P<pk>\d+)$1', views.JugadoraUpdate.as_view(), name='EditJugadora'),
    path(r'^borrar1/(?P<pk>\d+)$', views.JugadoraDelete.as_view(), name='DeleteJugadora'),

    path('login', views.login_request, name='Login'),
    path('register', views.register, name= 'Register'),
    path('logout', LogoutView.as_view(template_name='AppCoder/logout.html'), name='Logout'),
    path('editarUsuario', views.editarUsuario, name='EditarUsuario'),
    path('about/', views.acercaDeMi, name='AboutMe'),
   
    
]

MartuProyect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppCoder/', include('AppCoder.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppCoder/models.py
from django.db import models
from django.contrib.auth.models import User


class Club(models.Model):
    nombre = models.CharField(max_length=30)
    division =  models.CharField(max_length=2)
    deporte =  models.CharField(max_length=30)
   
class Jugadora(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    mail = models.EmailField(default='')
    club = models.CharField(max_length=30)

class Avatar(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank = True)

AppCoder/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class ClubFormulario(forms.Form):

    nombre = forms.CharField()
    division = forms.CharField()
    deporte = forms.CharField()

class JugadoraForm(forms.Form):
    nombre = forms.CharField()
    apellido = forms.CharField()
    mail = forms.EmailField()
    club = forms.CharField()

class RegistroFormulario(UserCreationForm):

    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir Contraseña", widget=forms.PasswordInput)
    
    last_name = forms.CharField()
    first_name = forms.CharField()

    class Meta:

        model = User
        fields = ['username', 'email', 'password1', 'password2', 'last_name', 'first_name']
        help_texts = {k:'' for k in fields} 

AppCoder/views.py
from msilib.schema import Class
from django.http import HttpResponse
from AppCoder.models import Avatar, Club, Jugadora
from django.shortcuts import render
from django.template import Template
from AppCoder.forms import ClubFormulario, JugadoraForm, RegistroFormulario
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy

def register(request):
    if request.method == 'POST':
    
        form = RegistroFormulario(request.POST) #LEER LA DATA DEL FORMULARIO DE INICIO DE SESION

        if form.is_valid():
            user = form.cleaned_data['username']
            form.save()

            return render(request, 'AppCoder/inicio.html', {'mensaje':"Usuario Creado"})
    else:
        form = RegistroFormulario()
    
    return render(request, 'AppCoder/registro.html', {'form': form})

def editarUsuario(request):

    usuario = request.user 

    if request.method == 'POST':

        miFormulario1 = RegistroFormulario(request.POST)
        
        if miFormulario1.is_valid():

            info3 = miFormulario1.cleaned_data

            usuario.username = info3['username']
            usuario.email = info3['email']
            usuario.password1 = info3['password1']
            usuario.password2 = info3['password2']
            usuario.save()

            return render(request, 'AppCoder/inicio.html')
    else:
        miFormulario1 = RegistroFormulario(initial={'username':usuario.username, 'email':usuario.email})
    
    return render(request, 'AppCoder/editarUsuario.html',{'miFormulario1':miFormulario1, 'usuario':usuario.username})


def login_request(request):

    if request.method == 'POST': #al presionar el boton iniciar sesion
        
        form = AuthenticationForm(request, data=request.POST) #LEER LA DATA DEL FORMULARIO DE INICIO DE SESION

        if form.is_valid():

            usuario= form.cleaned_data.get('username') #leer el usuario ingresado
            contra= form.cleaned_data.get('password')

            user=authenticate(username=usuario, password=contra) #buscar al usuario con los datos ingresados

            if user:  #si ha encontrado un usuario con esos datos

                login(request, user) #hacemos login
                #mostramos la pg de inicio con un mensaje de bienvenida
                return render(request, 'AppCoder/inicio.html', {'mensaje':f"Bienvenido {user}"})
            
        else: # si el formulario no es valido(no encuentra el usuario)
                #mostramos la pag de inicio junto a un mensaje de error
            return render(request, 'AppCoder/inicio.html', {'mensaje':"Error. Datos incorrectos"})
    
    else:
        
        form = AuthenticationForm() #mostrar el formulario

    return render(request, "AppCoder/login.html", {'form':form}) #vincular la vista con la plantilla de html


def club(request):

    if request.method == 'POST':

        miFormulario = ClubFormulario(request.POST) #aca llega la info del formulario

        print(miFormulario) #muestra en terminal

        if miFormulario.is_valid():        #comprobar si la info es valida

            informacion = miFormulario.cleaned_data

            club = Club(nombre=informacion['nombre'], division=informacion['division'], deporte=informacion['deporte']) #creo el curso con la info recivida

            club.save()

            return render(request, 'AppCoder/inicio.html') #una vez guardado mostramos la plantilla de inicio

    else:
        miFormulario = ClubFormulario()  #me muestra un formulario vacio


    return render(request, 'AppCoder/clubes/club.html', {'miFormulario':miFormulario})



class ClubList(LoginRequiredMixin, ListView):
    model = Club
    template_name = 'AppCoder/clubes/clubes_list.html'

class ClubDetalle(DetailView):
    model = Club
    template_name= 'AppCoder/clubes/club_detalle.html'

class ClubCreacion(CreateView):
    model = Club
    template_name= 'AppCoder/clubes/club_form.html'
    success_url= '/AppCoder/club/lista'
    fields= ['nombre', 'division', 'deporte']

class ClubUpdate(UpdateView):
    model = Club
    template_name= 'AppCoder/clubes/club_form.html'
    success_url= '/AppCoder/club/lista'
    fields= ['nombre', 'division', 'deporte']

class ClubDelete(DeleteView):
    model = Club
    template_name= 'AppCoder/clubes/club_confirm_delete.html'
    success_url= '/AppCoder/club/lista'

def jugadora(request):
  
     if request.method == 'POST':

        miFormulario = JugadoraForm(request.POST) 

        print(miFormulario) 

        if miFormulario.is_valid():        

            info1 = miFormulario.cleaned_data

            jugadora = Jugadora(nombre=info1['nombre'], apellido=info1['apellido'], mail=info1['mail'], club=info1['club'])  

            jugadora.save()

            return render(request, 'AppCoder/inicio.html') 

     else:
        miFormulario = JugadoraForm() 


     return render(request, 'AppCoder/jugadoras/jugadora.html', {'miFormulario': miFormulario})


class JugadoraList(LoginRequiredMixin, ListView):
    model = Jugadora
    template_name = 'AppCoder/jugadoras/jugadora_list.html'

class JugadoraDetalle(DetailView):
    model = Jugadora
    template_name= 'AppCoder/jugadoras/jugadora_detalle.html'

class JugadoraCreacion(CreateView):
    model = Jugadora
    template_name= 'AppCoder/jugadoras/jugadora_form.html'
    success_url= '/AppCoder/jugadora/lista'
    fields= ['nombre', 'apellido', 'mail', 'club']

class JugadoraUpdate(UpdateView):
    model = Jugadora
    template_name= 'AppCoder/jugadoras/jugadora_form.html'
    success_url= '/AppCoder/jugadora/lista'
    fields= ['nombre', 'apellido', 'mail', 'club']

class JugadoraDelete(DeleteView):
    model = Jugadora
    template_name= 'AppCoder/jugadoras/jugadora_form.html'
    success_url= '/AppCoder/jugadora/lista'
    fields= ['nombre', 'apellido','mail', 'club']


@login_required  
def inicio(request):
    avatares = Avatar.objects.filter(user=request.user.id)
    mensaje = 'Pagina oficial del Torneo Metropolitano de Hockey'
    return render(request, 'AppCoder/inicio.html',{'mensaje': mensaje, 'url':avatares[0].imagen.url})

def buscar(request):

    if request.GET['division']:

        division= request.GET['division']
        #curso = Curso.objects.filter(camada__icontains=camada) #icontains significa que el numero que buscamos esta dentro del numero de camada
        club = Club.objects.filter(division__iexact=division)

        return render(request, 'AppCoder/resultadosBusqueda.html', {'club':club, 'division':division})

    else:
        respuesta= 'No enviaste datos'

    return HttpResponse(respuesta)
  
def torneo(request):
     return render(request, 'AppCoder/torneo.html')

def acercaDeMi(request):
    return render(request, 'AppCoder/aboutMe.html' )

AppCoder/templates/AppCoder/aboutMe.html
{% extends "AppCoder/padre.html" %}

{% block contenidoModificable %}

<h1 style=color:lightblue>Acerca de mi</h1>
    
{% endblock %}

{% block contenidoModificable3 %} 
<p><em>Hola, mi nombre es Martina, tengo 20 años y soy de Buenos Aires, Argentina.Actualmente estoy cursando la carrera universitaria de Ciencia de Datos y me interesa la programacion. </p></em>

{% endblock %}

{% block contenido2 %} 
<li>Email: marti2409ortiz@gmail.com</li>
{% endblock %}

AppCoder/templates/AppCoder/curso.html
{% extends "AppCoder/padre.html" %}

{% load static %}


{% block contenidoModificable %}

<h1 style=color:lightblue>Cursos:</h1>


{% endblock %}


{% block contenido2 %} 

{% if miFormulario.errors %} 

<p style ='color:red'>Datos incorrectos</p>

{% endif %} 

<p>Cargar curso:

</p>
<form action="" method = "POST">{% csrf_token %}

     <table>

        {{miFormulario.as_table}}

     </table>

    <input type='submit' value="Enviar">
    <p>
       
    </p>
</form>

<p>
   Buscar curso por camada:
</p>

<form action="/AppCoder/buscar/" method="GET">{% csrf_token %}

   <input TYPE="number" name="camada" id="camada">
   <input type="submit" value="Buscar">

</form>


{% endblock %} 

AppCoder/templates/AppCoder/cursoFormulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% if miFormulario.errors %} 

        <p style ='color:red'>Datos incorrectos</p>

    {% endif %} 


    <form action="" method = "POST">{% csrf_token %}

            <table>

           {{miFormulario.as_table}}

            </table>

        <input type='submit' value="Enviar">

    </form>
</body>
</html>

AppCoder/templates/AppCoder/editarUsuario.html
{% extends "AppCoder/padre.html" %}


{% block contenidoModificable %}

<body>
    <h1 style=color:lightblue>Editar Perfil de {{usuario}}</h1>
<br>
    {% if miformulario1.errors %}
    <p style ='color:red'>Datos incorrectos</p>
    {% endif %}


    <form action="" method="POST">{% csrf_token %} 
        <table>

            {{ miFormulario1.as_table }}

        </table>
        <input type="submit", value="Enviar">

    </form>
</body>
{% endblock %}

AppCoder/templates/AppCoder/inicio.html
{% extends "AppCoder/padre.html" %}

{% block contenidoModificable %}
<h1 style=color:lightblue>{{mensaje}}</h1>
{% endblock %}

<br>
{% block contenidoModificable3 %} 
<div class="text-center">
    <img  height="40px" src="{{url}}" >
</div>
{% endblock %}

AppCoder/templates/AppCoder/login.html
{% extends "AppCoder/padre.html" %}

{% load static %}


{% block contenidoModificable %}
<body>
    <form action="" method="POST"> {% csrf_token %} 

        {{form.as_p}} 

        <button type="submit">Iniciar Sesion</button>
        
    </form>
</body>
{% endblock %}

AppCoder/templates/AppCoder/logout.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoModificable %}
<body>
    Has cerrado sesion.
</body>

{% endblock %} 

AppCoder/templates/AppCoder/padre.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Landing Page - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"
        type="text/css" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
        type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'AppCoder/css/styles.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'inicio' %}">Inicio</a>
            <a class="navbar-brand" href="{% url 'Jugadoras' %}">Jugadora</a>
            <a class="navbar-brand" href="{% url 'Clubes' %}">Club</a>
            <a class="navbar-brand" href="{% url 'Torneo' %}">Torneo</a>
            <a class="btn btn-secundary" href="{% url 'AboutMe' %}">About</a>


            {% if not request.user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'Login' %}">Iniciar</a>
            {% endif %}

            {% if request.user.is_authenticated %}
            <p class="text-muted small mb-4 mb-lg-0"> Hola {{user.username}}!</p>

            {% block contenidoAvatar %}
            {% endblock %}

            {% with first_image=user.avatar_set.first %}
            {% if first_image %}
            <a href="{{ first_image.imagen.url }}" target="_blank">
            <img src="{{ first_image.imagen.url }}" class="" style="max-width: 60px">
            {% endif %}
            {% endwith %}
            {% endif %}

                {% if not user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'Register' %}">Registrarse</a>
                {% endif %}


                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'EditarUsuario' %}">Editar Perfil</a>
                {% endif %}

                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'Logout' %}">Cerrar Sesion</a>
                {% endif %}
        </div>
    </nav>


    <!-- Masthead-->
    <header class="masthead">
        <div class="container position-relative">
            <div class="row justify-content-center">
                <div class="col-xl-6">
                    <div class="text-center text-white">
                        <!-- Page heading-->
                        <!--<h1 class="mb-5">Hola mate</h1>-->
                        {% block contenidoModificable %}

                        {% endblock %}

                        {% block contenidoModificable3 %}

                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>

    </header>

    {% block contenido2 %}
    {% endblock %}
    <!-- Footer-->
    <footer class="footer bg-light">

    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

AppCoder/templates/AppCoder/registro.html
{% extends "AppCoder/padre.html" %}

{% load static %}

{% block contenidoModificable %}
<body>
    <form action="" method="POST">{% csrf_token %} 
        {{form.as_p}}
        <button type="submit">Registrarse</button>
    </form>
</body>
{% endblock %}

AppCoder/templates/AppCoder/resultadosBusqueda.html
<p>Clubes de division {{division}} :</p>
{% if club %}
<ul>
{% for club in club %} 
    <li> {{club.nombre}} </li>
{% endfor %} 
</ul>
<p>
    <a  href='{% url "Clubes" %}'>Regresar</a>
 </p>
 
{% endif %}

AppCoder/templates/AppCoder/torneo.html
{% extends 'AppCoder/padre.html' %}

{% load static %}


{% block contenidoModificable %}

<h1 style=color:lightblue> Torneo Metropolitano de Hockey </h1>

{% endblock %}

{% block contenidoModificable3 %} 
<p><em>El torneo Metropolitano de Hockey Femenino es una competencia de hockey sobre cesped, en la que participan clubes de Buenos Aires, Argentina.</em></p>
{% endblock %}


{% block contenido2 %} 
<h3 style=color:rgb(70, 192, 233)> Clubes que participan del torneo: </h3>
   <form action="/AppCoder/club/lista" method="GET">{% csrf_token %}

      <input type="submit" value="lista de Clubes">
  
   </form> 

{% endblock %}